### ISSUE TITLE
Create build/run file

### ISSUE THREAD

**Issue by smaccoun** [smaccoun/elm-haskell-scaffold#1]

**Comment by sigrlami** [comment]
@smaccoun what do you need to build? I think even simple `make` file will be enough

**Comment by smaccoun** [comment]
@sigrlami Not totally sure yet, but one key piece would be something for setting up db info on first time clone. Right now I have the db name, username, password hardcoded in the haskell. Probably want to move to a config file that gets modified by a startup script which prompts the user the first time they run. Then runs the yarn install, elm package install, stack build etc. 

I left this open ended here. Just script(s) that are a convenience for any of

1. first time make
2. oft-repeated commands during development
3. Deployments where we may want test before doing doing a git push that our CI does (ie something along the lines of running a build -> docker compose -> eb deploy to test on server before commit).

Free range here to start something useful for whatever you are doing, and can evolve over time

**Comment by jetaggart** [comment]
I'm piloting the idea of shake. Usually in my development flow, having a
language based build file is useful (rake/Gradle) for automated tasks makes
life way easier, especially when it's in a language the devs understand.
Might be overkill​ for this template though. A shake example branch seems
useful though, the docs are pretty opaque for a simple example.

**Comment by jetaggart** [comment]
Also, usually like it orchestrate all db tasks from a build script rather
than the app itself. Think those are better handled by the app itself?

**Comment by sigrlami** [comment]
@jetaggart Hi, Jeff! From my point of view build scripts are useful when you have many stages to build final executable. This way you can create different flows with parameters which are useful for integration testing in CI and many-staged CD.

Steve @smaccoun mentioned parameters that shouldn't be changed often and even secured in some safe remote vault in case of environment breach and config is best place for it. You can have dev config along with code and production somewhere on S3. That's why I have another  [issue](https://github.com/smaccoun/elm-haskell-scaffold/issues/10) opened.

While `shake` is very interesting option, it takes time for developers to understand and build upon it, while every developer encountered `make`.

**Comment by jetaggart** [comment]
Hey Sergey, nice to meet you finally. After looking through `shake` I agree with you, `shake` is overkill for a simple web app. I'm going to keep piloting it for my own company, but I think it's too much for a simple starter app.

**Comment by sigrlami** [comment]
@jetaggart Nice to meet you too. Shake is cool project for advanced Haskeller.
